# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyorbital',
                'doc_host': 'https://Tom-TBT.github.io',
                'git_url': 'https://github.com/Tom-TBT/pyorbital',
                'lib_path': 'pyorbital'},
  'syms': {'pyorbital.core': {'pyorbital.core.say_hello': ('core.html#say_hello', 'pyorbital/core.py')}}}
