# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyorbital',
                'doc_host': 'https://Tom-TBT.github.io',
                'git_url': 'https://github.com/Tom-TBT/pyorbital',
                'lib_path': 'pyorbital'},
  'syms': { 'pyorbital.conversion': { 'pyorbital.conversion.decimal_to_dms': ('conversion.html#decimal_to_dms', 'pyorbital/conversion.py'),
                                      'pyorbital.conversion.dms_to_decimal': ('conversion.html#dms_to_decimal', 'pyorbital/conversion.py')},
            'pyorbital.core': { 'pyorbital.core.HelloSayer': ('core.html#hellosayer', 'pyorbital/core.py'),
                                'pyorbital.core.HelloSayer.__init__': ('core.html#hellosayer.__init__', 'pyorbital/core.py'),
                                'pyorbital.core.HelloSayer.say': ('core.html#hellosayer.say', 'pyorbital/core.py'),
                                'pyorbital.core.say_hello': ('core.html#say_hello', 'pyorbital/core.py')}}}
